# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      hadoop_branch:
        description: Name of the Hadoop branch to use
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      # Runs a single command using the runners shell
      - name: Clone Hadoop
        shell: bash
        run: |
            git config --system core.longpaths true
            git clone https://github.com/apache/hadoop ~/hadoop --single-branch --branch "$HADOOP_BRANCH" --depth=1
        env:
          HADOOP_BRANCH: ${{ inputs.hadoop_branch }}

      # Runs a set of commands using the runners shell
      - name: Run the build script
        run: |
          python build.py ~/hadoop

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: winutils
          path: results
