# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
            git config --system core.longpaths true
            git clone https://github.com/apache/hadoop ~/hadoop --single-branch --branch branch-3.3.1 --depth=1

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          python build_it.py ~/hadoop
