name: Build Hadoop Winutils

on:

  workflow_dispatch:
    inputs:
      hadoop_branch:
        description: Name of the Hadoop branch to use
        required: true

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      # Runs a single command using the runners shell
      - name: Clone Hadoop
        shell: bash
        run: |
            git config --system core.longpaths true
            git clone https://github.com/apache/hadoop ~/hadoop --single-branch --branch "$HADOOP_BRANCH" --depth=1
        env:
          HADOOP_BRANCH: ${{ inputs.hadoop_branch }}

      # Runs a set of commands using the runners shell
      - name: Run the build script
        run: |
          python build.py $HOME/hadoop

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: winutils
          path: results
